# SwiftLint configuration for FitDad Nudge

# Paths to include
included:
  - FitDadNudge
  - FitDadNudgeTests
  - FitDadNudgeUITests

# Paths to exclude
excluded:
  - Carthage
  - Pods
  - DerivedData
  - .build
  - ${PWD}/**/*.generated.swift

# Rules configuration
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - modifier_order
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

disabled_rules:
  - todo
  - trailing_whitespace

# Rule configuration
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - URL
    - url
    - uri
    - URI
    - i
    - j
    - k
    - x
    - y
    - z

function_parameter_count:
  warning: 6
  error: 8

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 15
  error: 20

file_header:
  required_pattern: |
    \/\/
    \/\/  .*\.swift
    \/\/  FitDadNudge
    \/\/
    \/\/  Created by .* on .*\.
    \/\/

# Custom rules
custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '(Array|Dictionary)(<.*>)?\s*\('
    capture_group: 1
    message: "Use array/dictionary literal syntax instead"
    severity: warning

  missing_docs:
    name: "Missing Docs"
    regex: '^\s*public(?!.*private\(set\)).*\{[^\}]*\}'
    match_kinds:
      - comment
    message: "Public declarations should be documented"
    severity: warning

  force_https:
    name: "Force HTTPS"
    regex: '(http(?!s):\/\/(?!localhost))'
    match_kinds: string
    message: "Use HTTPS instead of HTTP"
    severity: warning 